disabled_rules:
- colon
- trailing_whitespace
- opening_brace
- function_body_length
- type_body_length
- function_parameter_count
- file_length
- large_tuple
- line_length
- todo
- notification_center_detachment
- unused_closure_parameter
- redundant_string_enum_value
- redundant_void_return
- unused_optional_binding
- void_return

identifier_name:
    allowed_symbols: "_"
    min_length: 1
    max_length:
      warning: 90
      error: 1000
    excluded:
      - id
    validates_start_with_lowercase: false

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
